//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/InputActions/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""f940a5af-30b1-412f-89f2-c4cf2372f2d6"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""9ab14dd5-f2be-4a3a-b546-be00717ae578"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""1Hit"",
                    ""type"": ""Button"",
                    ""id"": ""5774f74a-9772-463f-a1eb-e7839725b121"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""3Hit"",
                    ""type"": ""Button"",
                    ""id"": ""01eba9c9-40a1-4b22-99e1-11b73305e783"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""5Hit"",
                    ""type"": ""Button"",
                    ""id"": ""44a1f5f1-5e16-4e38-b08d-e670c32c71bd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""7Hit"",
                    ""type"": ""Button"",
                    ""id"": ""2f050759-96ce-4072-ae54-45eaa59faa9a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""2Hit"",
                    ""type"": ""Button"",
                    ""id"": ""799fceec-a66d-4492-a866-49e40cbcba7a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""4Hit"",
                    ""type"": ""Button"",
                    ""id"": ""cf2b8adc-25af-4bdd-8485-96d19b28054c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""6Hit"",
                    ""type"": ""Button"",
                    ""id"": ""4f381383-07f0-4244-ba44-87e20fb16542"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""8Hit"",
                    ""type"": ""Button"",
                    ""id"": ""f40fc9e7-d77e-4682-80e7-7eecc362b88f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""1Parry"",
                    ""type"": ""Button"",
                    ""id"": ""dd5cce5c-ad82-4154-8dea-03c365e06ed1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""2Parry"",
                    ""type"": ""Button"",
                    ""id"": ""f7346027-e360-459e-a005-ebdee9ef028e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""3Parry"",
                    ""type"": ""Button"",
                    ""id"": ""7cb0fa0f-72d8-4d00-afde-5d6d7c9283a5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""4Parry"",
                    ""type"": ""Button"",
                    ""id"": ""8a52ff09-211a-45fe-8dcc-6854666012b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""5Parry"",
                    ""type"": ""Button"",
                    ""id"": ""5860192a-2ccf-4ee4-bfbd-3542f70d147f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""6Parry"",
                    ""type"": ""Button"",
                    ""id"": ""553c8cda-ed90-4431-92e1-cb34699582fc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""7Parry"",
                    ""type"": ""Button"",
                    ""id"": ""9ffb0520-c3fc-420b-8ff9-729014581090"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""8Parry"",
                    ""type"": ""Value"",
                    ""id"": ""a0a31491-798b-40a0-aae1-703f09fbc30f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""a9665932-01c5-4a67-b8da-e80ad8be7104"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0bf907c8-60f4-4c0f-b1f9-4221c8aae4de"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""fe8e076e-b8a4-444c-ac19-f0c69f6a5527"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""653b20da-419d-454c-b629-8626ebd54c74"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""15c3ae6d-c33f-44bf-8c28-8c521a00a6f0"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""4dd40d24-1a9b-4841-8f80-8ca148d10b7c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1656faf8-4cb3-4033-acd7-cd9f94cfebee"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c29b08d0-6fcf-45a0-9052-8f4c1eddb40f"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""16755bb2-97c8-4026-b381-48f1439cf83f"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ec3fb10f-74ef-4f26-8a2c-a37773a45e42"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c91d450f-e3b2-466c-b0a8-b89c466ecf9b"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""2Hit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fc9018d7-2a2a-4cdb-8793-4dd2666bd1b9"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""4Hit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d34aafa-5c01-48ef-a84c-2ae819123f5b"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""6Hit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""924b1763-ffdd-4abd-b5e1-035167f86bd8"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""8Hit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""68c4c72a-8b48-4f90-86ea-e17f324b44d4"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""1Hit"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""e91b6df1-7589-4bc1-a76e-0e2cd4ea022b"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""1Hit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""5477f2e9-a22c-44cc-8dcf-9495e554658f"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""1Hit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""597add06-1d78-4b77-b4c9-bd47c742fb53"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""3Hit"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""d1f1deb8-4525-4d51-97da-ae440257b584"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""3Hit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""68d5e4f2-24a4-4032-890b-f5f16065a8d9"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""3Hit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""6a04a0e4-9405-4c48-9dd0-13155734cd21"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""5Hit"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""664fdc16-fdd4-4167-bf90-1cb235d37cac"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""5Hit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""b3d93750-984f-4f63-b310-4ad3f59cc4c6"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""5Hit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""6ebdda65-b1b9-46b1-ac53-cfc4f67dcf80"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""7Hit"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""16e2344d-1b61-4df1-a84a-c24f6e6bd8e5"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""7Hit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""6a6a82dc-3101-466d-9163-36ee44f260ef"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""7Hit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""022ea7c1-a392-4717-a8ed-e87a55f644ab"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""2Parry"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""bb3e95ec-0fb3-4c3f-b57a-0dde28a04ea7"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""2Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""34c77dab-23c2-4556-a2a3-99f252b72e2c"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""2Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""7fd4eaa1-6303-4aba-9f27-a60d7045b139"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""8Parry"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""a11803ee-5082-4921-baed-566c3ee67901"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""8Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""bf925b46-a9df-4d7f-b8a1-b191b598604c"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""8Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""4a576901-c729-4c28-9f9c-88fb5618dc77"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""4Parry"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""e145bc1c-7168-4259-bd37-59bddadab677"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""4Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""984ed13c-bf45-4d16-ba02-f1b1858e5b20"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""4Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""3b1784b6-ebb8-4c42-ae30-0377670a648c"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""6Parry"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""30fd50c0-ffd8-4670-909f-a14de61a8389"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""6Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""a18efbd9-dd60-428b-8dae-4df25d918466"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""6Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""c9f69564-fff2-419f-bf08-c3c6750378be"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""1Parry"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""fddcf072-0d17-43f9-aa8d-60d3798a5f74"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""1Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""f47bdd51-29db-45b7-8f5c-f3427a5c46e0"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""1Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""4fa122c8-0451-4728-a782-f80a57ce988b"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""1Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""895d6acb-6a42-4cce-917d-9ef4afec81f7"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""3Parry"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""f4bf7d45-0e6e-4bcb-a1ae-308d4a0a2ef7"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""3Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""48bda4be-7e4f-460a-9148-450b67a9c485"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""3Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""6ab12cd3-3502-478f-990e-c0c9fe0f3f40"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""3Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""0d361586-cb69-47f4-93a2-a8d861beadce"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""5Parry"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""ff5c830b-e759-443a-aade-5f23f1e57827"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""5Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""35545d27-11a0-4c1f-8a18-1144503e41d2"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""5Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""73bc8f0a-729c-46c8-adc0-0c7dca57de66"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""5Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""e8eeed83-3c23-49c3-a119-8b8f67367dc6"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""7Parry"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""ced3520a-fbd3-4351-97f2-7f80e08c5513"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""7Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""b019ba8d-8a3a-49e2-9297-2b420d0742ff"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""7Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""ebba2f28-71ab-4c95-aa07-5497f9931a07"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""7Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard & Mouse"",
            ""bindingGroup"": ""Keyboard & Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player__1Hit = m_Player.FindAction("1Hit", throwIfNotFound: true);
        m_Player__3Hit = m_Player.FindAction("3Hit", throwIfNotFound: true);
        m_Player__5Hit = m_Player.FindAction("5Hit", throwIfNotFound: true);
        m_Player__7Hit = m_Player.FindAction("7Hit", throwIfNotFound: true);
        m_Player__2Hit = m_Player.FindAction("2Hit", throwIfNotFound: true);
        m_Player__4Hit = m_Player.FindAction("4Hit", throwIfNotFound: true);
        m_Player__6Hit = m_Player.FindAction("6Hit", throwIfNotFound: true);
        m_Player__8Hit = m_Player.FindAction("8Hit", throwIfNotFound: true);
        m_Player__1Parry = m_Player.FindAction("1Parry", throwIfNotFound: true);
        m_Player__2Parry = m_Player.FindAction("2Parry", throwIfNotFound: true);
        m_Player__3Parry = m_Player.FindAction("3Parry", throwIfNotFound: true);
        m_Player__4Parry = m_Player.FindAction("4Parry", throwIfNotFound: true);
        m_Player__5Parry = m_Player.FindAction("5Parry", throwIfNotFound: true);
        m_Player__6Parry = m_Player.FindAction("6Parry", throwIfNotFound: true);
        m_Player__7Parry = m_Player.FindAction("7Parry", throwIfNotFound: true);
        m_Player__8Parry = m_Player.FindAction("8Parry", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player__1Hit;
    private readonly InputAction m_Player__3Hit;
    private readonly InputAction m_Player__5Hit;
    private readonly InputAction m_Player__7Hit;
    private readonly InputAction m_Player__2Hit;
    private readonly InputAction m_Player__4Hit;
    private readonly InputAction m_Player__6Hit;
    private readonly InputAction m_Player__8Hit;
    private readonly InputAction m_Player__1Parry;
    private readonly InputAction m_Player__2Parry;
    private readonly InputAction m_Player__3Parry;
    private readonly InputAction m_Player__4Parry;
    private readonly InputAction m_Player__5Parry;
    private readonly InputAction m_Player__6Parry;
    private readonly InputAction m_Player__7Parry;
    private readonly InputAction m_Player__8Parry;
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @_1Hit => m_Wrapper.m_Player__1Hit;
        public InputAction @_3Hit => m_Wrapper.m_Player__3Hit;
        public InputAction @_5Hit => m_Wrapper.m_Player__5Hit;
        public InputAction @_7Hit => m_Wrapper.m_Player__7Hit;
        public InputAction @_2Hit => m_Wrapper.m_Player__2Hit;
        public InputAction @_4Hit => m_Wrapper.m_Player__4Hit;
        public InputAction @_6Hit => m_Wrapper.m_Player__6Hit;
        public InputAction @_8Hit => m_Wrapper.m_Player__8Hit;
        public InputAction @_1Parry => m_Wrapper.m_Player__1Parry;
        public InputAction @_2Parry => m_Wrapper.m_Player__2Parry;
        public InputAction @_3Parry => m_Wrapper.m_Player__3Parry;
        public InputAction @_4Parry => m_Wrapper.m_Player__4Parry;
        public InputAction @_5Parry => m_Wrapper.m_Player__5Parry;
        public InputAction @_6Parry => m_Wrapper.m_Player__6Parry;
        public InputAction @_7Parry => m_Wrapper.m_Player__7Parry;
        public InputAction @_8Parry => m_Wrapper.m_Player__8Parry;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @_1Hit.started -= m_Wrapper.m_PlayerActionsCallbackInterface.On_1Hit;
                @_1Hit.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.On_1Hit;
                @_1Hit.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.On_1Hit;
                @_3Hit.started -= m_Wrapper.m_PlayerActionsCallbackInterface.On_3Hit;
                @_3Hit.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.On_3Hit;
                @_3Hit.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.On_3Hit;
                @_5Hit.started -= m_Wrapper.m_PlayerActionsCallbackInterface.On_5Hit;
                @_5Hit.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.On_5Hit;
                @_5Hit.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.On_5Hit;
                @_7Hit.started -= m_Wrapper.m_PlayerActionsCallbackInterface.On_7Hit;
                @_7Hit.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.On_7Hit;
                @_7Hit.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.On_7Hit;
                @_2Hit.started -= m_Wrapper.m_PlayerActionsCallbackInterface.On_2Hit;
                @_2Hit.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.On_2Hit;
                @_2Hit.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.On_2Hit;
                @_4Hit.started -= m_Wrapper.m_PlayerActionsCallbackInterface.On_4Hit;
                @_4Hit.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.On_4Hit;
                @_4Hit.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.On_4Hit;
                @_6Hit.started -= m_Wrapper.m_PlayerActionsCallbackInterface.On_6Hit;
                @_6Hit.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.On_6Hit;
                @_6Hit.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.On_6Hit;
                @_8Hit.started -= m_Wrapper.m_PlayerActionsCallbackInterface.On_8Hit;
                @_8Hit.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.On_8Hit;
                @_8Hit.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.On_8Hit;
                @_1Parry.started -= m_Wrapper.m_PlayerActionsCallbackInterface.On_1Parry;
                @_1Parry.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.On_1Parry;
                @_1Parry.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.On_1Parry;
                @_2Parry.started -= m_Wrapper.m_PlayerActionsCallbackInterface.On_2Parry;
                @_2Parry.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.On_2Parry;
                @_2Parry.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.On_2Parry;
                @_3Parry.started -= m_Wrapper.m_PlayerActionsCallbackInterface.On_3Parry;
                @_3Parry.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.On_3Parry;
                @_3Parry.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.On_3Parry;
                @_4Parry.started -= m_Wrapper.m_PlayerActionsCallbackInterface.On_4Parry;
                @_4Parry.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.On_4Parry;
                @_4Parry.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.On_4Parry;
                @_5Parry.started -= m_Wrapper.m_PlayerActionsCallbackInterface.On_5Parry;
                @_5Parry.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.On_5Parry;
                @_5Parry.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.On_5Parry;
                @_6Parry.started -= m_Wrapper.m_PlayerActionsCallbackInterface.On_6Parry;
                @_6Parry.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.On_6Parry;
                @_6Parry.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.On_6Parry;
                @_7Parry.started -= m_Wrapper.m_PlayerActionsCallbackInterface.On_7Parry;
                @_7Parry.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.On_7Parry;
                @_7Parry.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.On_7Parry;
                @_8Parry.started -= m_Wrapper.m_PlayerActionsCallbackInterface.On_8Parry;
                @_8Parry.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.On_8Parry;
                @_8Parry.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.On_8Parry;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @_1Hit.started += instance.On_1Hit;
                @_1Hit.performed += instance.On_1Hit;
                @_1Hit.canceled += instance.On_1Hit;
                @_3Hit.started += instance.On_3Hit;
                @_3Hit.performed += instance.On_3Hit;
                @_3Hit.canceled += instance.On_3Hit;
                @_5Hit.started += instance.On_5Hit;
                @_5Hit.performed += instance.On_5Hit;
                @_5Hit.canceled += instance.On_5Hit;
                @_7Hit.started += instance.On_7Hit;
                @_7Hit.performed += instance.On_7Hit;
                @_7Hit.canceled += instance.On_7Hit;
                @_2Hit.started += instance.On_2Hit;
                @_2Hit.performed += instance.On_2Hit;
                @_2Hit.canceled += instance.On_2Hit;
                @_4Hit.started += instance.On_4Hit;
                @_4Hit.performed += instance.On_4Hit;
                @_4Hit.canceled += instance.On_4Hit;
                @_6Hit.started += instance.On_6Hit;
                @_6Hit.performed += instance.On_6Hit;
                @_6Hit.canceled += instance.On_6Hit;
                @_8Hit.started += instance.On_8Hit;
                @_8Hit.performed += instance.On_8Hit;
                @_8Hit.canceled += instance.On_8Hit;
                @_1Parry.started += instance.On_1Parry;
                @_1Parry.performed += instance.On_1Parry;
                @_1Parry.canceled += instance.On_1Parry;
                @_2Parry.started += instance.On_2Parry;
                @_2Parry.performed += instance.On_2Parry;
                @_2Parry.canceled += instance.On_2Parry;
                @_3Parry.started += instance.On_3Parry;
                @_3Parry.performed += instance.On_3Parry;
                @_3Parry.canceled += instance.On_3Parry;
                @_4Parry.started += instance.On_4Parry;
                @_4Parry.performed += instance.On_4Parry;
                @_4Parry.canceled += instance.On_4Parry;
                @_5Parry.started += instance.On_5Parry;
                @_5Parry.performed += instance.On_5Parry;
                @_5Parry.canceled += instance.On_5Parry;
                @_6Parry.started += instance.On_6Parry;
                @_6Parry.performed += instance.On_6Parry;
                @_6Parry.canceled += instance.On_6Parry;
                @_7Parry.started += instance.On_7Parry;
                @_7Parry.performed += instance.On_7Parry;
                @_7Parry.canceled += instance.On_7Parry;
                @_8Parry.started += instance.On_8Parry;
                @_8Parry.performed += instance.On_8Parry;
                @_8Parry.canceled += instance.On_8Parry;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard & Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void On_1Hit(InputAction.CallbackContext context);
        void On_3Hit(InputAction.CallbackContext context);
        void On_5Hit(InputAction.CallbackContext context);
        void On_7Hit(InputAction.CallbackContext context);
        void On_2Hit(InputAction.CallbackContext context);
        void On_4Hit(InputAction.CallbackContext context);
        void On_6Hit(InputAction.CallbackContext context);
        void On_8Hit(InputAction.CallbackContext context);
        void On_1Parry(InputAction.CallbackContext context);
        void On_2Parry(InputAction.CallbackContext context);
        void On_3Parry(InputAction.CallbackContext context);
        void On_4Parry(InputAction.CallbackContext context);
        void On_5Parry(InputAction.CallbackContext context);
        void On_6Parry(InputAction.CallbackContext context);
        void On_7Parry(InputAction.CallbackContext context);
        void On_8Parry(InputAction.CallbackContext context);
    }
}
